name: Python CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches:
      - '**'
  workflow_dispatch:

concurrency:
  group: "${{ github.workflow }}-${{ github.ref }}"
  cancel-in-progress: true

jobs:
  tests:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-20.04]
        toxenv: [py38-django42, py311-django42, py312-django42, py38-quality, py311-quality, py312-quality, translations]

    steps:
    - name: checkout repo
      uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Extract the Python version from tox environment
      run: |
        if [[ "${{ matrix.toxenv }}" =~ py[0-9]+ ]]; then
          PYTHON_VERSION=$(echo "${{ matrix.toxenv }}" | sed -E 's/py([0-9])([0-9]+).*/\1.\2/')
        else
          # Default version
          PYTHON_VERSION=3.8
        fi
        echo "PYTHON_VERSION=$PYTHON_VERSION" >> $GITHUB_ENV

    - name: setup python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ env.PYTHON_VERSION }}

    - name: Install translations dependencies
      if: ${{ startsWith(matrix.toxenv, 'translations') }}
      run: |
        sudo apt-get update
        sudo apt-get install -y gettext

    - name: Install Dependencies
      run: make requirements

    - name: Run Tests
      env:
        TOXENV: ${{ matrix.toxenv }}
      run: tox
